version: '3.8'
services:
  api:
    build: ./apps/api
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - meilisearch
  web-openindia:
    build: ./apps/web-openindia
    ports:
      - "3002:3000"
    env_file:
      - .env
    depends_on:
      - api
  web-ssu:
    build: ./apps/web-ssu
    ports:
      - "3003:3000"
    env_file:
      - .env
    depends_on:
      - api
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lms
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  meilisearch:
    image: getmeili/meilisearch:v1.7
    restart: always
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: masterKey
volumes:
  db_data:
  redis_data:
