name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            turbo-${{ runner.os }}-

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            apps/**/node_modules
            packages/**/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate SDK (codegen)
        run: pnpm generate:sdk

      - name: Check SDK drift
        run: |
          if ! git diff --quiet --exit-code packages/sdk; then
            echo "::error::SDK is out of date. Run 'pnpm generate:sdk' and commit the changes.";
            git --no-pager diff --name-only packages/sdk;
            exit 1;
          fi

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run unit tests
        run: pnpm test --if-present

      - name: Run e2e tests
        run: pnpm test:e2e

      - name: Always teardown services
        if: always()
        run: docker compose -f docker-compose.dev.yml down || true

      - name: Build
        run: pnpm build
